baseURL: /
languageCode: en-us
defaultContentLanguage: en
title: Mateus Studies
theme: cupper-hugo-theme
enableGitInfo: true

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  description: My studies
  homeMetaContent: Studies of Mateus Felipe Gonçalves (mateusfg7)
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  katex: true
  hideHeaderLinks: false
  search: true
  showThemeSwitcher: true
  defaultDarkTheme: false
  # navTitleText: Cupper Theme
  logoAlt: Just Me
  customCss:
    - css/custom.css

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Knowledge
      url: https://mfg-b.vercel.app/knowledge
      weight: 2

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
